import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/index.scss";

import { Header } from "@/widgets/Header";

import { ClientProvider } from "@/init/ClientProvider";

const InterFont = Inter({
  weight: ["400", "500"],
  variable: "--font-base",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable}`}>
        <ClientProvider>
          <Header />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
