import type { Metadata } from "next";
import { M_PLUS_Rounded_1c, Work_Sans } from "next/font/google";

import "@/styles/index.scss";

const geistSans = M_PLUS_Rounded_1c({
  weight: ["400", "500"],
  variable: "--font-alt",
  subsets: ["latin"],
});

const geistMono = Work_Sans({
  weight: ["400", "500"],
  variable: "--font-base",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
